ordermaster-starter:
  web:
    security:
      requestMatchers:
        - roles:
            - MANAGER
          urlPatterns:
            - /internal/manager/**

        - roles:
            - CLIENT
          urlPatterns:
            - /{cityId}/register/**

